### ISSUE TITLE
Add Commands Instead of Messages

### ISSUE THREAD

**Issue by 1tsak** [1tsak/OSC-Bot#1]
**The Bot is currently using messages with "!" instead of commands.**
 - You have to make a discord bot to use commands in place of general messages.
 - You can use the official discord js documentation to learn more about commands and how to register them: https://discordjs.guide/
 - You have to make the additions or changes and open the pull request mentioning this issue.

**Comment by Rajkumar-justcoder** [comment]
hey i would like to work on this

can u specify which commands to add like slash (/) commands or an normal cmd like !ping !info etc

**Comment by 1tsak** [comment]
@Rajkumar-justcoder sure, go ahead,
slash commands you can register those so that they will show in the discord command section.
Right Now it is using normal text match instead of commands.
If you have ideas for other commands other than which are already in code you can add them.

**Comment by Rajkumar-justcoder** [comment]
> @Rajkumar-justcoder sure, go ahead, slash commands you can register those so that they will show in the discord command section. Right Now it is using normal text match instead of commands. If you have ideas for other commands other than which are already in code you can add them.

so yeah 
i can add slash cmd and some other default cmd as serverinfo and userinfo and some more cmd me be

**Comment by Rajkumar-justcoder** [comment]
so can i remove old cmd which are prefix based and make fully / cmd based

**Comment by 1tsak** [comment]
@Rajkumar-justcoder Yes, but make sure you add the replies which are already there start and social just change the trigger to command.
Thanks

**Comment by Rajkumar-justcoder** [comment]
Yup i got that i will start working on it from tomorrow morning :v:
Thanks

**Comment by Rajkumar-justcoder** [comment]
Hey i have opened pr

**Comment by 1tsak** [comment]
Yes, thanks, merged.
